name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint with Ruff
        run: ruff check src/holyremix
      - name: Format with Black
        run: black --check src/holyremix
      - name: Type check with mypy
        run: mypy src/holyremix
      - name: Run tests
        run: pytest 